- name: download puppet repo file
  get_url: url=http://apt.puppetlabs.com/puppetlabs-release-trusty.deb
           dest=/tmp/puppetlabs-release-trusty.deb
- name: install puppetmaster repo
  command: dpkg -i /tmp/puppetlabs-release-trusty.deb

- apt: update-cache=yes cache_valid_time=3600
- name: dependencies
  action: apt name={{item}} state=present
  with_items:
    - puppetmaster
    - git
    - ruby-dev
    - make
    - apache2
    - libapache2-mod-passenger

- shell: "grep search /etc/resolv.conf  | awk '{print $2}'"
  register: domain_name

- name: enable apache modules
  command: a2enmod ssl headers passenger

- name: upload apache2 config
  template: src=puppetmaster.conf dest=/etc/apache2/sites-available/puppetmaster.conf

- name: enable puppet site
  command: a2ensite puppetmaster

- name: disable default site
  command: a2dissite 000-default

- name: disable puppet master webrick
  lineinfile: dest=/etc/default/puppetmaster regexp=^START= line=START=no

- name: apache rack directory
  file: 
    path: "{{ item }}"
    state: directory
    owner: puppet
  with_items:
    - /usr/share/puppet/rack/puppetmasterd
    - /usr/share/puppet/rack/puppetmasterd/public
    - /usr/share/puppet/rack/puppetmasterd/tmp

- name: puppet environments dir
  file: path=/etc/puppet/environments state=directory owner={{ remote_user }}

- name: upload puppet.conf
  copy: src={{ puppet_conf }} dest=/etc/puppet/puppet.conf
  notify: restart puppetmaster

- name: initialize git repo
  sudo: no
  git: repo={{ git_repo }}
       version={{ git_head }}
       dest=/etc/puppet/environments/{{ git_puppet_env }}
       accept_hostkey=yes

- service: name=apache2 state=stopped
- service: name=puppetmaster state=started
- pause: seconds=5
- service: name=puppetmaster enabled=no state=stopped
- service: name=apache2 enabled=yes state=restarted
